config/routes.rb
SocialPoster::Application.routes.draw do
  
  root "static_pages#home"
  
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  match '/vcontact', to: 'vkontakte_connection#contact', via: 'get'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages, only: [:create, :destroy, :show]
  resources :authorisations, only: [:create, :destroy]
  
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  
  match '/authorisations', to: 'authorisations#show', via: 'get'
  
  get '/auth/:provider/callback', to: 'authorisations#create'
  get '/auth/failure', to: 'authorisations#failure'
  
end

app/models/authorisation.rb
class Authorisation < ActiveRecord::Base  
  belongs_to :user  
end

app/models/facebook_message.rb
class FacebookMessage < ActiveRecord::Base
  belongs_to :message
end

app/models/linkedin_message.rb
class LinkedinMessage < ActiveRecord::Base
  belongs_to :message
end

app/models/message.rb
class Message < ActiveRecord::Base
  
  belongs_to :user
  
  has_one :twitter_message, dependent: :destroy
  has_one :facebook_message, dependent: :destroy
  has_one :linkedin_message, dependent: :destroy
  has_one :tumblr_message, dependent: :destroy
  has_one :twitter_message, dependent: :destroy
  has_one :vkontakte_message, dependent: :destroy
  
  default_scope -> { order('created_at DESC') }
  
end

app/models/tumblr_message.rb
class TumblrMessage < ActiveRecord::Base
  belongs_to :message
end

app/models/twitter_message.rb
class TwitterMessage < ActiveRecord::Base
  belongs_to :message
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :authorisations, dependent: :destroy
  has_many :messages, dependent: :destroy
  
  
  has_secure_password validations: false
  
  
  before_create :create_remember_token  
  before_save { self.email = email.downcase }
  
  class << self
    def new_remember_token
      SecureRandom.urlsafe_base64
    end
    
    def encrypt(token)
      Digest::SHA1.hexdigest(token.to_s)
    end    
  end
  
  private
    
    def create_remember_token
      self.remember_me = User.encrypt(User.new_remember_token)
    end
    
end

app/models/vkontakte_message.rb
class VkontakteMessage < ActiveRecord::Base
  belongs_to :message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  helper_method :current_user
  helper_method :user_signed_in?
  
end

app/controllers/authorisations_controller.rb
class AuthorisationsController < ApplicationController
  
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy
  
  include AuthorisationsExtra
  
  def create
    
    auth_hash = read_authhash(request.env['omniauth.auth'])
    
    params[:provider] = auth_hash[:provider]
    params[:uid] = auth_hash[:uid]
    params[:token] = auth_hash[:token]
    params[:secret] = auth_hash[:secret]
    params[:secret] = "secret" if auth_hash[:secret].length < 1
    
    outcome = CreateAuthorisation.run(params, user: current_user)
    
    if outcome.success?
      flash[:info] = "> #{outcome.result.provider} connected"
    else
      flash[:error] = "> #{outcome.inspect} not connected"
    end
    
    redirect_to root_url
  end
  
  def destroy
    @authorisation.destroy
    redirect_to root_url
  end

  private
  
  def correct_user
    @authorisation = current_user.authorisations.find_by(id: params[:id])
    redirect_to root_url if @authorisation.nil?
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy
  
  def create
    
    params[:facebook_message][:text] = params[:facebook_message][:text].sub("<br>", "")
    params[:linkedin_message][:text] = params[:linkedin_message][:text].sub("<br>", "")
    params[:twitter_message][:text] = params[:twitter_message][:text].sub("<br>", "")
    params[:vkontakte_message][:text] = params[:vkontakte_message][:text].sub("<br>", "")
    
    outcome = CreateMessage.run(params, user: current_user)
    
    @send_results = {}
    
    if outcome.success?
      
      @message = outcome.result
      
      @send_results = MessageSendersExtra.do_send_message(@message)
      
      flash[:success] = "message is sent"
    else
      flash[:error] = "message is not sent"
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_url
  end
  
  private
  
  def correct_user
    @message = current_user.messages._by(id: params[:id])
    redirect_to root_url if @message.nil?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    
    user = User.find_by(email: params[:session][:email].downcase)
    
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'сообщаю, что ошибка'
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  
    return if not current_user
    
    @message = current_user.messages.build
    @message.facebook_message = FacebookMessage.new
    @message.linkedin_message = LinkedinMessage.new
    @message.tumblr_message = TumblrMessage.new
    @message.twitter_message = TwitterMessage.new
    @message.vkontakte_message = VkontakteMessage.new
    
    @message.facebook_message.text = ''
    @message.linkedin_message.text = ''
    @message.tumblr_message.text = ''
    @message.twitter_message.text = ''
    @message.vkontakte_message.text = ''

  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :signed_in_user, only: [:index, :edit, :update, :show]
  before_action :correct_user,   only: [:edit, :update]
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @messages = @user.messages.paginate(page: params[:page])
  end
  
  def index
    @users = User.all
  end
  
  def create
    
    outcome = UserCreate.run(params[:user])
    
    user = outcome.result
    
    if outcome.success?
      flash[:success] = "> #{outcome.result.name} created"
      
      sign_in user
      redirect_to user
    else
      flash[:error] = "> not created %s" % outcome.inspect
      @user = User.new
      render 'new'
    end
    
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
  
    outcome = UserUpdate.run(params[:user], user: User.find(params[:id]))
    
    user = outcome.result
    
    if outcome.success?
      flash[:success] = "> #{outcome.result.name} updated"
      
      sign_in user
      redirect_to user
    else
      flash[:error] = "> not updated %s" % outcome.inspect
      @user = User.find(params[:id])
      render 'edit'
    end
    
  end
  
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title)
    base_title = "Social Poster"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
end

app/helpers/authorisations_helper.rb
module AuthorisationsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in user
    remember_me = User.new_remember_token
    cookies.permanent[:remember_me] = remember_me
    user.update_attribute(:remember_me, User.encrypt(remember_me))
    
    self.current_user = user
  end
  
  def sign_out
    self.current_user = nil
    
    cookies.delete(:remember_me)
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_me = User.encrypt(cookies[:remember_me])
    @current_user ||= User.find_by(remember_me: remember_me)
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "please, sign in"
    end
  end
  
  def store_location
    session[:return_to] = request.url
  end
  
  
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.haml
%footer{ class: "footer" }
  %small
    %a{ href: "http://social-poster.herokuapp.com" }
      Social Poster
  
  %nav
    %ul
      %li
        =link_to "About", about_path
      %li
        =link_to "Contact", contact_path
      %li
        %a{ href: "https://github.com/kiote/social-poster" }
          GitHub

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "Social Poster", root_path, id: "logo"
      
      %nav
        %ul{ class: "nav pull-right" }
          %li
            =link_to "Home", root_path
          %li
            =link_to "Help", help_path
          
          - if signed_in?
            %li=link_to "Users", users_path
            
            %li#fat-menu.dropdown
              
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
                
              %ul.dropdown-menu
                %li
                  = link_to "Profile", current_user
                %li
                  = link_to "Settings", edit_user_path(current_user)
                %li{ class: "divider" }
                %li
                  =link_to "Sign out", signout_path, method: "delete"
          - else
            %li=link_to "Sign in", signin_path
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = full_title(yield(:title))
      
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    
    = render 'layouts/shim'
    
  %body
    = render 'layouts/header'
    
    %div.container
      
      - flash.each do |key, value|
        %div{ class: "alert alert-#{key}"}=value
      
      = yield
      
      = render 'layouts/footer'
      
      = debug(params) if Rails.env.development?

app/views/layouts/social_poster.html.haml
!!!
%html
  %head
    
    %title SocialPoster
    
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    
    / Le styles
    
    %link{:href => "/assets/bootstrap/css/bootstrap.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/assets/bootstrap/js/google-code-prettify/prettify.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/assets/bootstrap-wysihtml5/css/bootstrap-wysihtml5.css", :rel => "stylesheet", :type => "text/css"}/
    
    :css
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }
      
      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      
      .btn.jumbo {
        font-size: 20px;
        font-weight: normal;
        padding: 14px 24px;
        margin-right: 10px;
        \-webkit-border-radius: 6px;
        \-moz-border-radius: 6px;
        border-radius: 6px;
        width: 100px;
      }
      
      .width_500 {
        width: 500px;
      }
      
      .width_300 {
        width: 300px;
      }
    
    = yield :head
    
  %body
    
    = yield
    
    = debug(params) if Rails.env.development?
    
    / Le javascript
    / \==================================================
    / Placed at the end of the document so the pages load faster
    
    %script{:src => "/assets/bootstrap/js/jquery.js"}
    %script{:src => "/assets/bootstrap/js/bootstrap-transition.js"}
    %script{:src => "/assets/bootstrap/js/bootstrap-alert.js"}
    %script{:src => "/assets/bootstrap/js/bootstrap-modal.js"}
    %script{:src => "/assets/bootstrap/js/bootstrap-dropdown.js"}
    %script{:src => "/assets/bootstrap/js/bootstrap-scrollspy.js"}
    %script{:src => "/assets/bootstrap/js/bootstrap-tab.js"}
    %script{:src => "/assets/bootstrap/js/bootstrap-tooltip.js"}
    %script{:src => "/assets/bootstrap/js/bootstrap-popover.js"}
    %script{:src => "/assets/bootstrap/js/bootstrap-button.js"}
    %script{:src => "/assets/bootstrap/js/bootstrap-collapse.js"}
    %script{:src => "/assets/bootstrap/js/bootstrap-carousel.js"}
    %script{:src => "/assets/bootstrap/js/bootstrap-typeahead.js"}

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  %div{id: "error_explanation"}
    %div.alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")} .
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          * #{msg}

app/views/shared/_linkedin_form.html.haml
= form_for(@linkedin_message) do |f|
  = render 'shared/error_messages', object: f.object
  %div.field
    = f.text_area :text, placeholder: "compose new twitter message", class: "textarea"
  = f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_message_form.html.haml
= form_for(@message) do |f|

  = render 'shared/error_messages', object: f.object
  
  %div.field
    = fields_for @message.facebook_message do |m|
      = m.text_area :text, placeholder: "compose new facebook message", class: "textarea"
    
    = fields_for @message.linkedin_message do |m|
      = m.text_area :text, placeholder: "compose new linkedin message", class: "textarea"
    
    = fields_for @message.tumblr_message do |m|
      = m.text_area :text, placeholder: "compose new tumblr message", class: "textarea"
    
    = fields_for @message.twitter_message do |m|
      = m.text_area :text, placeholder: "compose new twitter message", class: "textarea"
    
    = fields_for @message.vkontakte_message do |m|
      = m.text_area :text, placeholder: "compose new vkontakte message", class: "textarea"
    
  = f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_user_info.html.haml
/ %a{ href: "#{user_path(current_user)}" }
/   #{ gravatar_for current_user }

%h1
  = current_user.name
%br
%span
  = pluralize(current_user.messages.count, "message")
%span
  = pluralize(current_user.authorisations.count, "authorisation")

app/views/shared/_vkontakte_form.html.haml
= form_for(@vkontakte_message) do |f|
  = render 'shared/error_messages', object: f.object
  %div.field
    = f.text_area :text, placeholder: "compose new twitter message", class: "textarea"
  = f.submit "Post", class: "btn btn-large btn-primary"